### ISSUE TITLE
Curricular episode should describe more nuanced responses to pull requests

### ISSUE THREAD

**Issue by colinmorris** [carpentries/maintainer-onboarding#14]
This passage is near the end of [episode 2](https://carpentries.github.io/maintainer-onboarding/02-curricular/index.html):

> **Introduction of new material to a lesson** A decision to implement these changes (or not) should be made by at least two members of the Lesson Team. The first Maintainer to review the change leaves a comment indicating whether it should be approved (we often use the comment “LGTM” (looks good to me) to indicate approval). The second Maintainer to review can either merge (if both have approved the changes) or write a comment to the contributor explaining why the change won’t be implemented and close the issue or PR.

At the very least, I think there should be a third option for Maintainer 2 to say "looks good, except for X and Y". i.e. the contribution is a good idea overall, but the author needs to make a couple changes before it's ready to merge.

I would think that should be a much more frequent outcome than summarily closing. Given that one Maintainer has already approved the changes, it seems odd that the 2nd Maintainer would decide that it's so fundamentally and irredeemably flawed that it should just be closed without any further discussion.

**Comment by remram44** [comment]
Definitely! I don't think merge or close are the only two alternatives.

It is also common in GitHub projects to mark all this with labels (in addition to replying to the contributor of course). This makes it easier to get an overview of the issues to which no one has responded, the ones that are pre-approved, the ones that are pending more work from the author, etc. But I think adding standard labels to the lessons is outside the scope of this issue 😬

**Comment by ErinBecker** [comment]
Thanks @colinmorris and @remram44, very good points! Could you put in a PR to fix the wording here and introduce the third option? 

@remram44 - the SWC lessons to have standard issue labels (http://swcarpentry.github.io/lesson-example/08-maintenance/index.html), but other labels are commonly added by Maintainers in addition to these standards.

**Comment by ErinBecker** [comment]
Closed with https://github.com/carpentries/maintainer-onboarding/pull/18
