### ISSUE TITLE
Create roster of maintainer teams

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/maintainer-onboarding#15]
Raised in Maintainer onboarding discussion. Would like to have list of Maintainers on each team level (Lesson, Technology, etc) with contact info.

**Comment by chendaniely** [comment]
We can help curate the list by using the following lesson feeds:

- https://feeds.carpentries.org/lessons.json
- https://feeds.carpentries.org/all_badged_people.json

**Comment by ErinBecker** [comment]
For privacy reasons, we are unable to share individual Maintainer contact information with the full Maintainer community in a roster as requested in this issue. Instead, we have the ability to create lesson team specific Slack channels and/or TopicBox lists on request. We also put individual Maintainers for a single lesson in contact and update that contact when a Maintainer joins or leaves a lesson team.
