### ISSUE TITLE
Discussion of how to use tags for issues

### ISSUE THREAD

**Issue by angela-li** [carpentries/maintainer-onboarding#32]
It would be useful to include a mention in here of how to use tags to mark issues as a maintainer. What tags are recommended for what use cases? What does each tag mean when attached to an issue?

Perhaps a link to a dynamic wiki/document where the tags are spelled out would be helpful?

**Comment by fmichonneau** [comment]
Great idea. The current description of the labels is here: https://docs.carpentries.org/topic_folders/maintainers/github_labels.html

**Comment by angela-li** [comment]
Hi @fmichonneau - if you could take a look at the PR I submitted with this fix (#33) and let me know if it looks good, I'd appreciate it!

**Comment by angela-li** [comment]
Looks like @ErinBecker merged this PR - thanks all for the speedy response!
