### ISSUE TITLE
Social Aspects of Lesson Maintenance revisions

### ISSUE THREAD

**Issue by angela-li** [carpentries/maintainer-onboarding#35]
Starting an issue to keep track of feedback on the first lesson in this series, based on this [Maintainer RFC.](https://github.com/carpentries/maintainer-RFCs/issues/8) 

Please comment below with any feedback you have on how we can improve the Social Aspects portion of this lesson!

--- 

- how to interact with the other maintainers (process, specific times/ways/technologies)
- how to proceed with PRs (e.g. consensus, up to each maintainer, etc)
- how to coordinate with the respective curriculum advisory board in case "major" issues/PRs are raised
- etiquette with maintainers on the same lesson and with contributors
- suggestions on dealing with disagreements
- suggestions on dealing with abandoned PRs
- Getting fellow maintainers active, particularly if they are experienced or have been involved in early lesson development is critical. The "sunsetting" or "Emeritus" status process needs attention.
- Receiving Issue and PR requests from members of the Carpentries organization may need to be addressed, as these can be scary. (In particular, see next topic)
- If individuals are having trouble learning a specific task, create or offer "Tips and Tricks" on that task. Be able to ask for specific help formally within the safe maintainers community. This will help with new maintainer retention.

Non-technical component should explain how a Carpentries maintainer should interact with:

Contributors
- how to request changes?
- how to accept/reject a PR?
- how to deal with objections from contributors?
- how to deal with unusual contributors (rude/busy/change-it-all)?
- what to do with abandoned PRs/issues?

Other maintainers
- Etiquette and dealing with disagreements that Lauren mentioned above
- Other non-technical issues: questions that don't fall into any other category (dealing with difficult situations).

**Comment by ErinBecker** [comment]
Closing this issue as outdated.
