### ISSUE TITLE
Curricular Aspects of Lesson Maintenance revisions

### ISSUE THREAD

**Issue by angela-li** [carpentries/maintainer-onboarding#36]
Starting an issue to keep track of feedback on the second lesson in this series, based on this [Maintainer RFC](https://github.com/carpentries/maintainer-RFCs/issues/8).

Please comment below with any feedback you have on how we can improve the Curricular Aspects portion of this lesson!

---

- what changes should be accepted/rejected to lesson material?
- how to coordinate with the respective curriculum advisory board in case "major" issues/PRs are raised, etc.
- re-iteration/ in-depth lesson on how to build a lesson from a pedagogical point of view (formative assessments, learning objectives, Bloom's taxonomy etc) would be a good idea
- If re-writes of ANY kind are suggested ("combine", "split", "omit", "expand", "change name" etc.), that lesson needs a development page (make this process easy, for example by adding a "Development" tag to the Issue or PR). I've seen a few lessons flourish when the engaged maintainers have the opportunity to develop.
- How to handle issues with interdependent lessons.

**Comment by ErinBecker** [comment]
Thanks for putting together these notes @angela-li. I'm closing this issue based on the updates that have been made to Maintainer Onboarding in the past three years.
