### ISSUE TITLE
Broken Jekyll Link

### ISSUE THREAD

**Issue by kelseygonzalez** [carpentries/maintainer-onboarding#40]
Episode 3 says "Follow the i[nstructions for installing](https://swcarpentry.github.io/lesson-example/setup#optional-jekyll-setup-for-lesson-development) Jekyll and its dependencies. "
This link is broken.

**Comment by ErinBecker** [comment]
Thanks for this issue @kelseygonzalez - the link should be https://carpentries.github.io/lesson-example/setup#jekyll-setup-for-lesson-development. I'll make that fix now!

**Comment by kelseygonzalez** [comment]
Thanks for fixing this @ErinBecker !

**Comment by ErinBecker** [comment]
Fixed with https://github.com/carpentries/maintainer-onboarding/commit/1de850966bedf2412c3da1bd3879699752086c44

**Comment by ErinBecker** [comment]
There are probably other broken links! Please let me know if you find any. 😄
