### ISSUE TITLE
Add general logistics to episode 1

### ISSUE THREAD

**Issue by chendaniely** [carpentries/maintainer-onboarding#42]
Want to make sure everyone can access:

1. TopicBox and the maintainer's thread / Setup email forwarding
2. Slack group + Maintainer's channel
3. Community Calendar and can see the maintainer meetings

The emails should all be done before the onboarding, and we can use the first part of the class to check and the instructor can fix anyone who was missed afterwards.

**Comment by ErinBecker** [comment]
Thanks for these notes @chendaniely. I've been very remiss in keeping the issues up to date in this repo. 😱 The elements you identified above are all included now in https://carpentries.github.io/maintainer-onboarding/03-communicate-maintainers.html.
