### ISSUE TITLE
Lesson Release Process update

### ISSUE THREAD

**Issue by chendaniely** [carpentries/maintainer-onboarding#44]
In the [3rd episode](https://carpentries.github.io/maintainer-onboarding/03-infrastructure/index.html),
there is a secion on lesson release process that links to @rgaiacs. @zkamvar mentioned that this is something that @fmichonneau is involved with now. Is there an updated set of wording we should use here? or some document I should link to?

**Comment by fmichonneau** [comment]
the short paragraph that is already there looks pretty good. We are tentatively planning a new release of all lessons later this year and we can look into updating the information about the release process then.

**Comment by zkamvar** [comment]
@fmichonneau, I think there is relevant information that's missing is the second paragraph (emphasis mine)

> If your lesson is in a mature state, your level of involvement in the lesson development process will be less intense than that described above. The mature SWC and DC lessons go through a new lesson release every six months. At this point, the lessons go through clean-up (including resolving old issues and PRs) and are submitted to Zotero to create a new DOI for that version.
>
> **[FIXME: ask Raniere for some text here about what Maintainers do during lesson release.]**

As someone who has never seen the lesson release process, this question of what the maintainers are expected to do or not do remains unclear.

There are also other issues with this particular episode: 

 - we haven't done Issue Bonanzas or Bug BBQs in some time
 - there is no lesson release checklist (the link circles back to the same page)
 - do lessons get published only once or is the process cyclical? If it's cyclical, do lesson go through the entire process again?

**Comment by ErinBecker** [comment]
I've been very remiss in keeping the issues list updated. My apologies. The current version of Maintainer Onboarding does not include any reference to lesson release or lesson publication, as these are processes we are now conducting "as needed" (e.g. when a lesson first becomes official, or a major change is adopted).
