### ISSUE TITLE
Colorblindness-friendly updates to contributor/maintainer flowchart

### ISSUE THREAD

**Issue by ndporter** [carpentries/maintainer-onboarding#64]
The flowchart in "[Maintainers and Forked Repositories](https://carpentries.github.io/maintainer-onboarding/04-infrastructure/index.html#maintainers-and-forked-repositories)" in the infrastructure episode uses shades of red and green that are difficult for people with the most common form of colorblindness/color-impairment (including me) to tell apart. See https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/color-blindness/types-color-blindness. 

It would be excellent if that were updated to more accessible color combinations.

**Comment by ErinBecker** [comment]
Thank you @ndporter! I'll investigate updating the flowchart. 

@chendaniely - do you have an svg version of this diagram?

**Comment by ErinBecker** [comment]
Pinging @brynnelliott. The diagram being referred to is [this one](https://raw.githubusercontent.com/carpentries/maintainer-onboarding/gh-pages/fig/git-maintainer_contributor_diagram.png). We currently only have it as a png and so can't go in and edit the line colors directly. Do you know of any workarounds that can convert png to something vector? Even if it's a lossy conversion?
