### ISSUE TITLE
Transition to Workbench

### ISSUE THREAD

**Issue by zkamvar** [carpentries/maintainer-onboarding#69]
This lesson will be converted to use [The Carpentries Workbench][workbench]
To prevent accidental reversion of the changes, we are temporarily revoking
write access for all collaborators on this lesson:

 - [ ] @chendaniely (push)
 - [ ] @katrinleinweber (push)
 - [x] @vinisalazar (push)
 - [x] @ErinBecker (push)
 - [x] @tobyhodges (just here for the ride)

If you no longer wish to have write access to this repository, you do not
need to do anything further.

1. What you can expect from the transition 📹: https://carpentries.github.io/workbench/beta-phase.html#beta
2. How to update your local clone 💻: https://carpentries.github.io/workbench/beta-phase.html#updating-clone
3. How to update (delete) your fork (if you have one) 📹: https://carpentries.github.io/workbench/faq.html#update-fork-from-styles

If you wish to regain write access, please re-clone the repository on your machine and
then comment here with `I am ready for write access :rocket:` and the
admin maintainer of this repository will restore your permissions.

If you have any questions, please reply here and tag @zkamvar

[workbench]: https://carpentries.github.io/workbench

**Comment by zkamvar** [comment]
Hi Toby and @vinisalazar. I am so sorry I completely missed this when you commented -_-

Last week was kind of a 🗑️ 🔥 for me, but I have given you write access!

**Comment by vinisalazar** [comment]
No worries Zhian, thank you :)

**Comment by zkamvar** [comment]
As the current maintainers have regained their access, I am going to close this issue.
