### ISSUE TITLE
Contributing guide does not include Library Carpentry

### ISSUE THREAD

**Issue by bencomp** [carpentries/maintainer-onboarding#87]
Whereas the README file links to Software, Data and Library Carpentry, the Contributing Guide only includes links to Software and Data Carpentry. Other contributing guides also include links to The Carpentries website.

I did update several links in this guide in #85 but didn't update these references yet.

**Comment by zkamvar** [comment]
Thank you, @bencomp! 

As a bit of background, this particular lesson was [transitioned on 2023-03-17](https://github.com/carpentries/maintainer-onboarding/commit/b8c64857b57937bb46e434659f081f195cf2209c#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055), which was before we updated the CONTRIBUTING templates, so they are hilariously out of date 🙈 

I will go ahead and bring in a copy from the workbench template and replace all the FIXME links.
