### ISSUE TITLE
Keypoints and objectives are missing in episode 6

### ISSUE THREAD

**Issue by bencomp** [carpentries/maintainer-onboarding#89]
In episode 6, The Carpentries Git Workflow, the learning objectives and keypoints are both "List Here". I wanted to suggest some based on the contents and the questions, but then I realised that the focus of the narrative may not really answer the questions. I don't see anything about reviewing pull requests (except for a link to GitHub's documentation) and making changes to pull requests is not mentioned at all.

This is a (presumably) known issue that I just wanted to highlight. This issue could in a way be considered a duplicate of #37, which discusses what technical topics should be discussed in this lesson. (Maintainers are probably also aware of the need to update references to the `gh-pages` branch, now that The Workbench is in use and all changes should go to the `main` branch. That is a different issue.)

**Comment by tobyhodges** [comment]
Closed by #99

**Comment by tobyhodges** [comment]
Reviewing and editing PRs are covered in the separate [GitHub skill-up for Maintainers](https://carpentries.github.io/github-skill-up-maintainers/)
